# Generated by Django 5.2.3 on 2025-08-18 16:52

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0002_disease_donorprofile_allergies_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donorprofile',
            name='diseases',
        ),
        migrations.DeleteModel(
            name='Disease',
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='diseases',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('diabetes', 'Diabetes'), ('hypertension', 'Hypertension'), ('asthma', 'Asthma'), ('thyroid', 'Thyroid'), ('heart_disease', 'Heart Disease'), ('none', 'None')], max_length=200),
        ),
    ]
