# Generated by Django 5.2.3 on 2025-06-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(max_length=5, unique=True)),
                ('units', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
