# Generated by Django 5.2.3 on 2025-08-18 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='hospital',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='request_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='request_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='urgency',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
    ]
