# Generated by Django 5.2.3 on 2025-08-20 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0003_alter_bloodrequest_blood_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodrequest',
            name='request_date',
        ),
        migrations.RemoveField(
            model_name='bloodrequest',
            name='request_time',
        ),
    ]
