# Generated by Django 5.2.3 on 2025-08-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('donor', 'Donor'), ('recipient', 'Recipient')], default='recipient', max_length=10),
        ),
    ]
