# Generated by Django 5.2.3 on 2025-10-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('nurse', 'Nurse'), ('staff', 'Staff'), ('patient', 'Patient'), ('donor', 'Donor'), ('recipient', 'Recipient')], default='recipient', max_length=10),
        ),
    ]
